import type { Metadata } from 'next'
import { PT_Sans } from 'next/font/google'
import './UI/globals.css'

const pT_Sans = PT_Sans({ subsets: ['latin'], weight: ["400", "700"] })

export const metadata: Metadata = {
  title: 'Login | Sakura Coffee Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={pT_Sans.className}>{children}</body>
    </html>
  )
}
