import { Analytics } from "@vercel/analytics/react"
import type { Metadata } from 'next'
import { PT_Sans } from 'next/font/google'
import './UI/globals.css'
import { Providers } from './providers'

const pT_Sans = PT_Sans({ subsets: ['latin'], weight: ["400", "700"] })

export const metadata: Metadata = {
  title: 'Login | Sakura Coffee Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={pT_Sans.className}>
        <Providers >
          {children}
          <Analytics />
        </Providers>
      </body>
    </html>
  )
}
